# Generated by Django 3.2.7 on 2022-04-03 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasify_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bk_time',
        ),
    ]
