# Generated by Django 4.0.2 on 2022-05-08 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasify_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='st_id',
            new_name='bk_id',
        ),
        migrations.RemoveField(
            model_name='status',
            name='st_desc',
        ),
    ]
