# Generated by Django 4.0.2 on 2022-05-07 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasify_admin', '0002_remove_booking_bk_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='a_is_admin',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
