# Generated by Django 4.0.2 on 2022-05-08 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leasify_admin', '0002_rename_st_id_status_bk_id_remove_status_st_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='bk_id',
            new_name='st_id',
        ),
        migrations.AddField(
            model_name='status',
            name='st_desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
