# Generated by Django 3.2.7 on 2021-12-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasify_admin', '0002_auto_20211205_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='owner',
            fields=[
                ('o_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('o_type', models.CharField(max_length=30)),
                ('o_name', models.CharField(max_length=30)),
                ('o_email', models.EmailField(max_length=254, unique=True)),
                ('o_phno', models.CharField(max_length=13)),
                ('o_add', models.CharField(max_length=200)),
                ('o_pass', models.CharField(max_length=20)),
                ('otp', models.CharField(max_length=10, null=True)),
                ('otp_used', models.IntegerField(default=0)),
                ('is_admin', models.IntegerField(null=True)),
                ('o_gender', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'owner',
            },
        ),
    ]
