# Generated by Django 3.2.7 on 2021-12-05 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasify_admin', '0003_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='c_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='owner',
            name='o_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='house_details',
            fields=[
                ('h_id', models.AutoField(primary_key=True, serialize=False)),
                ('h_add', models.CharField(max_length=200)),
                ('h_img', models.CharField(max_length=200)),
                ('h_name', models.CharField(max_length=100)),
                ('h_rent', models.IntegerField()),
                ('h_type', models.CharField(max_length=100)),
                ('h_parking', models.CharField(max_length=10)),
                ('h_lift', models.CharField(max_length=100)),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasify_admin.owner')),
            ],
            options={
                'db_table': 'House Details',
            },
        ),
    ]
