# Generated by Django 4.0.2 on 2022-05-07 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasify_admin', '0003_remove_admin_a_is_admin_delete_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='c_is_admin',
        ),
    ]
