# Generated by Django 3.2.7 on 2021-12-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasify_admin', '0004_auto_20211205_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='house_details',
        ),
    ]
