# Generated by Django 3.2.7 on 2021-12-05 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasify_admin', '0005_auto_20211205_1838'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='area',
            table='Area',
        ),
    ]
