# Generated by Django 3.2.7 on 2021-12-05 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasify_admin', '0006_alter_area_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='house_details',
            fields=[
                ('h_id', models.AutoField(primary_key=True, serialize=False)),
                ('h_add', models.CharField(max_length=200)),
                ('h_imgpath', models.CharField(max_length=200)),
                ('h_name', models.CharField(max_length=100)),
                ('h_rent', models.IntegerField()),
                ('h_desc', models.CharField(max_length=300)),
                ('h_type', models.CharField(max_length=100)),
                ('h_parking', models.CharField(max_length=10)),
                ('h_lift', models.CharField(max_length=100)),
                ('a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasify_admin.area')),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasify_admin.owner')),
            ],
            options={
                'db_table': 'House Details',
            },
        ),
    ]
