# Generated by Django 3.2.7 on 2021-12-05 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasify_admin', '0007_house_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='house_gallery',
            fields=[
                ('gallery_id', models.AutoField(primary_key=True, serialize=False)),
                ('hg_imgpath', models.CharField(max_length=200)),
                ('h_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasify_admin.house_details')),
            ],
            options={
                'db_table': 'House Gallery',
            },
        ),
    ]
