# Generated by Django 3.2.7 on 2021-12-05 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasify_admin', '0008_house_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='pg_details',
            fields=[
                ('pg_id', models.AutoField(primary_key=True, serialize=False)),
                ('pg_add', models.CharField(max_length=200)),
                ('pg_imgpath', models.CharField(max_length=200)),
                ('pg_name', models.CharField(max_length=100)),
                ('pg_rent', models.IntegerField()),
                ('pg_desc', models.CharField(max_length=300)),
                ('pg_beds', models.IntegerField()),
                ('pg_for', models.CharField(max_length=10)),
                ('pg_food', models.CharField(max_length=10)),
                ('pg_wifi', models.CharField(max_length=10)),
                ('pg_tv', models.CharField(max_length=10)),
                ('a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasify_admin.area')),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasify_admin.owner')),
            ],
        ),
    ]
