# Generated by Django 3.2.7 on 2021-12-06 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasify_admin', '0009_pg_details'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='house_details',
            table='House_Details',
        ),
        migrations.AlterModelTable(
            name='house_gallery',
            table='House_Gallery',
        ),
        migrations.AlterModelTable(
            name='pg_details',
            table='PG_details',
        ),
    ]
