# Generated by Django 3.2.7 on 2021-12-06 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasify_admin', '0010_auto_20211206_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='pg_gallery',
            fields=[
                ('pg_gallery_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgg_imgpath', models.CharField(max_length=200)),
                ('pg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasify_admin.pg_details')),
            ],
            options={
                'db_table': 'PG_Gallery',
            },
        ),
    ]
