# Generated by Django 3.2.7 on 2021-12-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasify_admin', '0011_pg_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='tiffin_owner',
            fields=[
                ('to_id', models.AutoField(primary_key=True, serialize=False)),
                ('to_name', models.CharField(max_length=30)),
                ('to_email', models.EmailField(max_length=254, unique=True)),
                ('to_phno', models.CharField(max_length=13)),
                ('to_add', models.CharField(max_length=200)),
                ('to_pass', models.CharField(max_length=20)),
                ('otp', models.CharField(max_length=10, null=True)),
                ('otp_used', models.IntegerField(default=0)),
                ('to_gender', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Tiffin_Owner',
            },
        ),
    ]
