# Generated by Django 3.2.7 on 2021-12-06 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasify_admin', '0012_tiffin_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='tiffin_details',
            fields=[
                ('tiff_id', models.AutoField(primary_key=True, serialize=False)),
                ('tiff_title', models.CharField(max_length=100)),
                ('tiff_type', models.CharField(max_length=30)),
                ('tiff_desc', models.CharField(max_length=300)),
                ('tiff_imgpath', models.CharField(max_length=200)),
                ('tiff_price', models.IntegerField(max_length=10)),
                ('to_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasify_admin.tiffin_owner')),
            ],
            options={
                'db_table': 'Tiffn_Details',
            },
        ),
    ]
