# Generated by Django 3.2.7 on 2021-12-07 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasify_admin', '0013_tiffin_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='status',
            fields=[
                ('st_id', models.AutoField(primary_key=True, serialize=False)),
                ('st_desc', models.CharField(max_length=50)),
                ('h_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasify_admin.house_details')),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasify_admin.owner')),
                ('pg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasify_admin.pg_details')),
                ('tiff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasify_admin.tiffin_details')),
                ('to_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasify_admin.tiffin_owner')),
            ],
            options={
                'db_table': 'Status',
            },
        ),
    ]
