# Generated by Django 3.2.7 on 2021-12-07 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasify_admin', '0014_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('noti_id', models.AutoField(primary_key=True, serialize=False)),
                ('noti_desc', models.CharField(max_length=300)),
                ('noti_date', models.DateField()),
                ('st_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasify_admin.status')),
            ],
            options={
                'db_table': 'Notification',
            },
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('feed_date', models.DateField()),
                ('feed_desc', models.CharField(max_length=300)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasify_admin.customer')),
                ('h_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasify_admin.house_details')),
                ('pg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasify_admin.pg_details')),
                ('tiff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasify_admin.tiffin_details')),
            ],
            options={
                'db_table': 'Feedback',
            },
        ),
    ]
