# Generated by Django 3.2.7 on 2021-12-16 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasify_admin', '0016_auto_20211216_1914'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='admin',
        ),
    ]
